CHEAT_KEEP1_KILL_ALL = 0
CHEAT_KEEP1_ONLY_ONE_FOE = 0
CHEAT_KEEP2_GAMBLER_GIVE_ALL_MONEY = 0

CHEAT_CORINTH_KILL_ALL = 0
CHEAT_CORINTH_DEBUG_NAMES = 0

CHEAT_CAVES2_KILL_CENTEPIDES = 0
CHEAT_CAVES2_SKIP_CENTEPIDES = 0

CHEAT_ORC_FORT_DEBUG_NAMES = 0
CHEAT_GLOBAL_DEBUG_NAMES = 0

ALL_FOES_PEACFULL = 0